version: "3.9"
services:
  bedrock_asiaminor:
    build:
      context: asiaminor/
    network_mode: none
  bedrock_arabia:
    build:
      context: arabia/
    network_mode: none
  latineast_asiaminor:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    depends_on:
      - bedrock_asiaminor
    network_mode: none
  anatolia:
    build:
      context: anatolia/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_asiaminor
  balkans:
    build:
      context: balkans/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_asiaminor
  central_europe:
    build:
      context: central_europe/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_asiaminor
  cyprus:
    build:
      context: cyprus/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_asiaminor
  europe_mediterranean:
    build:
      context: europe_mediterranean/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_asiaminor
  europe_anatolia:
    build:
      context: europe_anatolia/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_asiaminor
  levant:
    build:
      context: levant/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_asiaminor
  levant_anatolia:
    build:
      context: levant_anatolia/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_asiaminor
  niledelta:
    build:
      context: niledelta/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_asiaminor
  latineast_arabia:
    build:
      context: ./
      dockerfile: Dockerfile.arabia
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    depends_on:
      - bedrock_arabia
    network_mode: none
  southwest_asia:
    build:
      context: southwest_asia/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_arabia
  arabian_peninsula:
    build:
      context: arabian_peninsula/
      args:
        PROJECT: ${COMPOSE_PROJECT_NAME}
    volumes:
      - ./pdf:/pdf
    network_mode: none      
    depends_on:
      - latineast_arabia
   
